workflows:
  ios-release:
    name: AG-ID iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: AGID
    environment:
      xcode: latest
    scripts:
      - name: Unpack project
        script: unzip -o ag-id-ios.zip -d .
      - name: Install Capacitor
        script: npm install
      - name: Initialize keychain
        script: keychain initialize
      - name: Fetch signing files from Apple
        script: app-store-connect fetch-signing-files "au.com.ag-id.app" --type IOS_APP_STORE --create
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Set up signing
        script: xcode-project use-profiles
      - name: Set build number
        script: cd ios/App && agvtool new-version -all $BUILD_NUMBER
      - name: Build app
        script: xcode-project build-ipa --project ios/App/App.xcodeproj --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
